### ISSUE TITLE
Implement disk-integrated model function fits

### ISSUE THREAD

**Issue by maxmahlke** [NASA-Planetary-Science/sbpy#112]
Hi everyone, I'd like to contribute to the sbpy development. Specifically, the fitting routine for the different disk-integrated models in the sbpy.photometry.core module. I saw that there's already a [placeholder](https://sbpy.readthedocs.io/en/latest/api/sbpy.photometry.DiskIntegratedModelClass.html#sbpy.photometry.DiskIntegratedModelClass.fit) in the code. I was looking for a package which is able to retrieve MPC observations and fit photometric models for my own research, so this is a nice opportunity to contribute, if no one else is already working on an implementation.

Some thoughts I noted down after a look at the photometry.core code:

- Currently, the photometric model has to be instantiated with the respective parameters (`hg = HG1G2() # TypeError`).  When the model is supposed to be fit to the phase curve, that shouldn't be necessary (as the example already in place shows). There has to be a change here, but I'm unfamiliar with the astropy `Parameter` class, so I can't yet say where exactly.
- This might be sbpy/astropy policy that I am unfamiliar with, but why should the input of the fit function be restricted to sbpy.data.Ephem objects? Something like `params, chi2 = HG1G2().fit(phi_array, mag_array)` could be clear and easier for users unfamiliar with the package structure
- The fit method is part of the DiskIntegratedModelClass and is inhereted by LinearPhaseFunc and HG12BaseClass (and HG1G2, HG12 accordingly). I would suggest sticking closely to the reference implementation of the [Helsinki HG1G2 tools](https://wiki.helsinki.fi/display/PSR/HG1G2+tools), where they use np.linalg.lstsq for the minimization, so all models (current + not implemented) inheriting from DiskIntegratedModelClass would need to be expressed as linear matrix equations to solve them

Let me know what you think, and other considerations you might have for this method.

Cheers

Max

**Comment by maxmahlke** [comment]
I believe the second point in my list is related to the discussion in #61, though it seems that you agreed on the methods handling list and array inputs as well and converting implicitly, unlike the doc string suggests.

**Comment by mkelley** [comment]
Great to hear that you are interested in contributing, thanks for contacting us.  I think @jianyangli is the lead for `photometry`, so he can address your questions with authority.

My opinion is that sbpy should be aligned with whatever approach `astropy.modeling` uses.  Initializing HG1G2 with values represents a set of initial conditions before fitting.  See http://docs.astropy.org/en/stable/modeling/index.html#simple-1-d-model-fitting for an example.  This is a typical requirement for optimization routines, no?  Although ideally we would work with `astropy.modeling`, I recognize that it is still in development.  I'll ask the maintainers if they recommend affiliated packages use the API or not.

Regarding the use of `Ephem`, our philosophy is that our methods should work with any dictionary-like object that returns `Quantity` objects.  Just as we discussed in #61, if an object passed to `fit` is not an instance of `Ephem` then it can be used to initialize a new `Ephem` object, and we preserve the benefits of the `Ephem` class.  I am all for flexibility, so allowing an alternative set of parameters as arguments is acceptable to me, but our priority should be support for `Ephem` objects.  I think a reasonable goal for v0.1 is to make sure we don't have methods and doc strings that conflict with this approach.  Thanks for pointing that out.

**Comment by mkelley** [comment]
OK, I've asked about `modeling`, if it is stable enough for use in affiliated packages.  Thomas Robitaille says, "yes, it is used in the gwcs package extensively for example, so I think it's stable enough to use. We are still working through some issues with models that have units in some corner cases. Also, don't create composite models by combining classes, only instances, as combining classes is going to be deprecated."

**Comment by mommermi** [comment]
Thanks, Max, I think we can use any help out there! But for final design questions, I would refer to @jianyangli, who is in charge of `photometry`.

A few comments in addition to those already provided by @mkelley 
* Personally, I would also prefer the approach of `hg=HG1G2()` and then assign the parameters if you want to, for instance, compute magnitudes. But that is something we should discuss with @jianyangli 
* I fully agree with @mkelley  here.
* @jianyangli can you comment on this?

Max, feel free to sign up for our sbpy slack for further discussions: sbpy.slack.com (I really have to add this link to the sbpy.org website...)

**Comment by mommermi** [comment]
@maxmahlke  one thing I forgot to mention: if you need a tool to pull observations reported to the MPC, have a look at this: [astroquery PR #1350](https://github.com/astropy/astroquery/pull/1350)

**Comment by jianyangli** [comment]
Hello Max, first of all, thank you for your interest in contributing.  Just as many other community developed packages, we rely on the contribution from as many interested people as possible to be successful.

Here are my responses to your thoughts:

1. Good suggestion.  In fact in my personal library I always set default parameters for all the models classes that I create.  This way, a model class can be instantiated without supplying any parameters as `hg = HG1G2()` in fitting, so users don't have to guess the parameters before they fit data.  I will update the code for this.
1. As we discussed in [#61](https://github.com/NASA-Planetary-Science/sbpy/pull/61) and pointed out by @mkelley , we agreed to make the input flexible but emphasize the `Ephem` class.
1. I'm now actually debating whether we should provide a `.fit()` method in the model class.  The goal here should be to implement the model classes but not restricting users from how they fit it.  From the convenience of users, we should do this, or even provide a class method, something like `.from_data()` to instantiate a model class by fitting data directly.  We probably could allow users to set the fitter as a parameter to the related methods.  But I'd like to hear what you all think.
    1. On the other hand, the way that a model is implemented will often affect the way we fit it.  Panttilä et al. (2016) suggested that a non-linear fitting approach works better than the linearized model form.  So I think it should be a good idea to stick to what we have now.  I don't think we have to stick to what the Helsinki tools do, as long as our code returns the same results.

**Comment by maxmahlke** [comment]
Thanks for the responses, looking forward to contribute!

I think we're agreeing on the first two points I mentiond,

- the user is able to instantiate the model class instance without parameters (default values are used), but can choose to provide them as a set of initial coniditions for a chosen fitting routine
- the data input should be flexible enough to handle dictionary-like objects but converts to and encourages the `Ephem` class

@jianyangli, if I understand your third point correctly, I agree that the user should be able to choose between linear and non-linear fitting. Maybe via a parameter in the fit method call. Penttilä+ 2016 state that non-linear is advisable for low accuracy or a low number of observations (<10), so we could set linear as default and print a warning if the non-linear routine might perform better, e.g. 

    from sbpy.photometry import HG
    from sbpy.data import Misc
    eph = Misc.mpc_observations('Bennu')
    hg = HG1G2()
    params, cov, chi2 = hg.fit(eph)  # linear=True is default
    
    > WARNING: Fewer than 10 datapoints, fit might be improved by setting linear=False, see Penttilä+ 2016

I'd say this is straight-forward for the user and covers most use cases. In terms of how to implement this, I'm not sure I understand your last paragraph, specifically "the way that a model is implemented will often affect the way we fit it". I have little experience when it comes to writing `astropy` code, mostly been on the user side so far. Could you explain some more?

**Comment by jianyangli** [comment]
The H, G1, G2 model is defined as a linear combination of the three base functions in flux space (Eqs. 1-3, Penttilä et al 2016).  But it's nonlinear in magnitude space.  This is what I meant by "the way the model is implemented affects the way we fit it.  This is just like when we fit parameter c in an exponential model y = exp(c*x), we can either fit it by nonlinear minimization directly, or linearize it to log(y) = c*log(x) and fit it by linear minimization.

Given that the model is devised to describe magnitude-phase relationship, fitting in linear space will make the data at high phase angle (low flux) underweighted.  I believe this is why a nonlinear fitting approach generally performs better, for both poor and good observational data (quality and number of points).  For this reason, I don't think it's really necessary to implement our own linear minimization code like what Penttilä's online tool did.  Why don't we just simply utilize the well tested and maintained nonlinear fitting routines already in `astropy` to perform the fitting?  This will not only be simple for us (and for users as well), but also more reliable and robust.

With that all said, again, I still doubt that we should include a `.fit()` method in the model class, because a model class doesn't have to be associated with a fitting approach.  In addition, the fitting process for all `astropy` models are all the same:

```
model = ModelClass(parameters)
fitter = FitterClass()
fitted_model = fitter(model, x, y)
```

In this sense, a `.fit()` method, if necessary, should really be implemented in the base class of all `astropy` models.  What do you think, @mommermi @mkelley , @migueldvb , @maxmahlke ?

**Comment by mommermi** [comment]
I would prefer to stick to the `astropy` rules and guidelines as much as possible, so I would advocate for using `astropy` fitters. However, in that case, we should probably provide some clear examples in the docs and the function docstrings. A `.fit()` function would in the end only serve as a wrapper for the `astropy` fitter and make a bunch of implicit assumptions on what the user (might) want.

**Comment by mkelley** [comment]
I love convenience, but conceptually, I think leaving the fitting to the Fitters is better.  Models have parameters and functional forms, Fitters optimize models.  Model.fit() doesn't "fit" this paradigm.  It is was definitely worth considering, though.

**Comment by maxmahlke** [comment]
Ok I understand your reasoning, thanks for clarifying @jianyangli. For now, I'll write a script which retrieves MPC observations using `astroquery.mpc` as @mommermi implemented in [PR #1350](https://github.com/astropy/astroquery/pull/1350), and fits the `sbpy` photometry models to the observations using `astropy.modeling`. Maybe later we can turn this into an example for the docs.

**Comment by mommermi** [comment]
> Maybe later we can turn this into an example for the docs
Yes, that'd be a great example!

**Comment by jianyangli** [comment]
OK then, let's keep the `.fit()` in our base class for photometric models as a wrapper for convenience, and provide a default fitter, some like:

```
from astropy.modeling.fitting import LevMarLSQFitter

Class PhotometricModel():

    def fit(x, y, fitter=None, return_fitter=False, **kwargs):
        if fitter is None:
            fitter = LevMarLSQFitter()
        model = fitter(self, x, y, **kwargs)
        if return_fitter:
            return model, fitter
        else:
            return model
```

The option for returning fitter is to make the statistical information of the fitting available.  Also, as I mentioned earlier, I will probably also implement a class method `.from_data()` to initialize the model directly from data by fitting:

```
Class PhotometricModel():

    @classmethod
    def from_data(cls, x, y, fitter=None, **kwargs):
        model = cls().fit(x, y, fitter=fitter, **kwargs)
        return model
````

If you all think these thoughts are reasonable and useful, I'll go ahead and implement it.

**Comment by anatheana** [comment]
Hi, my comments on the fitting (but not on the programming logic in sbpy). I would advise strongly to use nonlinear version of fitting, and do it in the magnitude space. The weighting and the residuals are completely different in flux and magnitude spaces. In the linear flux space, the residuals are strongly nonsymmetric, and that's why I would avoid linear fitting.

I tested some of the nonlinear fitting routines in scipy.optimize, and found out that the 'SLSQP' is producing the best results (finds smallest Chi^2 and is also fast). One important point is, that one should use boundaries for the parameter (G1 and G2) values in the optimizing routine, otherwise one might end up with non-physical phase curve (i.e., not monotonically decreasing in mag).  I coded a fitting routine for myself based on scipy.optimze, and it looks like this:

~~~~
import scipy.optimize as sco

# Fit H,G-system
def fit_hg(data, x0=[6,0.12]):
    cv = ({'type': 'ineq', 'fun': lambda x: x[1]},
          {'type': 'ineq', 'fun': lambda x: 1-x[1]})
    return sco.minimize(sse_hg,x0,args=data,constraints=cv,method='SLSQP')
###

# Fit H,G12-system
def fit_hg12(data):
    cv1 = ({'type': 'ineq', 'fun': lambda x: x[1]+0.0818919},
           {'type': 'ineq', 'fun': lambda x: 0.2-x[1]})
    cv2 = ({'type': 'ineq', 'fun': lambda x: x[1]-0.2},
           {'type': 'ineq', 'fun': lambda x: 0.909714-x[1]})
    res1 = sco.minimize(sse_hg12,[6,0.12],args=data,constraints=cv1,method='SLSQP')
    res2 = sco.minimize(sse_hg12,[6,0.32],args=data,constraints=cv2,method='SLSQP')
    if(res1.fun < res2.fun):
        return res1
    else:
        return res2

# Fit H,G1,G2-system
def fit_hg1g2(data, x0=[6,0.1,0.1]):
    cv = ({'type': 'ineq', 'fun': lambda x: x[1]},
          {'type': 'ineq', 'fun': lambda x: x[2]},
          {'type': 'ineq', 'fun': lambda x: 1-x[1]-x[2]})
    return sco.minimize(sse_hg1g2,x0,args=data,constraints=cv,method='SLSQP')
###
~~~~

where the sse-functions compute the sum-of-squares between the data and the model with given parameters.

The code above does only the fitting. If one needs to have some standard deviation or confidence interval estimates on the fitted parameters, something else needs to be done. Actually, for H,G12 the statistical errors for the G12-parameter might be problematic in the case where the fit ends up close to the value G12=0.2 where the model derivative is not continuous...

**Comment by jianyangli** [comment]
Hi @anatheana , thank you very much for your input.  Yes we will only implement the non-linear version of the H, G1, G2 and H, G12 models in magnitude space, and we can make `astropy.modeling.fitting.SLSQPLSQFitter()` fitter as the default fitter.  I will look into `astropy.modeling` module and see how we can put constraints like 1-G1-G2=0 as model default.

One question about the constraints for H, G12 system in your example:  I think the constraints in your example is for the original version of H, G12 system as in Muinonen et al. (2010), correct?  Do you advise us to implement the improved version of H, G12 system as in Penttilä et al. (2016), or maybe both?

**Comment by anatheana** [comment]
Hi,
The constraints for H,G12 are indeed for the year 2010 'official' version of H,G12. On the other hand, I do think that the 2010-version G12 has some problems with the discontinues on the derivative at G12=0.2. The statistical parameter errors might be impossible to derive if the fit ends up at G12=0.2. On the other hand, having several systems can be somewhat confusing. Anyway, implementing both might be better idea.

**Comment by jianyangli** [comment]
@anatheana after some tests, I'd like to stick to `~astropy.modeling.fitting.LevMarLSQFitter` instead of `SLSQPLSQFitter` for model fitting, because I think the former is more robust than the latter.  For example, when I pulled the magnitude data of (1862) Apollo from MPC, and fitted an HG model, the `SLSQPLSQFitter` failed, while the `LevMarLSQFitter` returns the results right away.  Please let me know if you have further concerns.  If you like, I can share you my Jupyter notebook for testing.

Also, I'm a little reluctant to build the parameter constraints into the default model class definition.  In my recent work, I fitted Bennu's disk-integrated phase function from OSIRIS-REx imaging data to the H, G12 model as in your 2016 paper, and returned negative value for the G12.  If I constrain G12>0, then the fit converges to G12=0.  Since these models are numerical and their parameters don't carry much physical meaning (at least for me), I think we should allow them to be unbounded.  If users want to put bounds to the parameters when fitting the models, they can do by themselves, but it may not be a good idea to make the bounds a default.  What do you think?

Thanks!

**Comment by anatheana** [comment]
For the best fitting method, I trust your tests and I don't have any concerns.

It's also OK to not bound the fit parameters, but then I hope that the users remember to use some cautiousness. I don't think that the G1,G2-parameters are physical in any way, but my only concern is that the phase function should be monotonically decreasing (or non-increasing) function in -mag. So it comes back to G1*phi1 + G2*phi2 + (1-G1-G2)*phi3 being decreasing function of phase angle, and also non-negative.

The idea with the bounds 0<=G1, 0<=G2, 0<=1-G1-G2 is that then the phase function would surely be decreasing, because all the phi-functions are. Problem is, that some combinations of G1 and G2 not exactly fulfilling the requirements might also produce decreasing phase function in -mag, but there is really no other than numerical ways to ensure that.

**Comment by mommermi** [comment]
@jianyangli @anatheana Do we want to issue a warning if the phase curve is not monotonically decreasing or if the slope parameters are outside the bounds? Would that be feasible?

**Comment by anatheana** [comment]
Yes, that could work.

**Comment by jianyangli** [comment]
@anatheana Thank you for your input.  If people use the model to fit actual data, which are always monotonically decreasing, then they will not reach a model that is not monotonically decreasing.  So I think this should not be a concern.

But I do like the suggestion by @mommermi .  Let me add warnings to the setters of model parameters.

**Comment by jianyangli** [comment]
Well, could someone (@mommermi @mkelley @anatheana or anyone who subscribed this thread) point me to the right place where I can overload the "setters" of model parameters?  I went through the code for [`astropy.modeling.Model`](http://docs.astropy.org/en/stable/_modules/astropy/modeling/core.html#Model), but couldn't find the right place.  Looks like `Model` dynamically generates parameter attributes from the information stored in `Model._param_metrics`, but I couldn't find out how it let us directly assign a value to a parameter attribute...

**Comment by mommermi** [comment]
As far as I know, models don't really have setters. Instead, values are simply passed to the `.evaluate` method. You could add a check there, or maybe it is enough to simply add a warning to the `bounds` method in case the boundaries are reached.

**Comment by mkelley** [comment]
I don't understand models.  I'd recommending raising the problem with the astropy #modeling slack channel.

**Comment by jianyangli** [comment]
OK, guys, thanks for your suggestions.  I added warnings in the `.evaluate` method.  Probably not the best place, because warnings are issued every time the model is evaluated, but at least it works for now.

The threshold for HG model is G<=1.194, for H, G1, G2 is G1>=0, G2>=0, and G1+G2<=1, and for HG12 (both versions) G>=-0.70 and G<=1.30.  I found the bounds for G and G12 manually by numerically calculating the first derivative of phase function model.  The case of G1, G2 is too complicated so I just adopted the suggestion by @anatheana .  Please let me know if you have any suggestions and/or concerns regarding these boundary settings.

PR #127 is updated.

**Comment by anatheana** [comment]
I'm not a Python expert, and definitely not an astropy expert. However, it sounds like too heavy to warn with (every?) evaluation. Model fitting routines can easily travel to these regions, which would issue warnings (?) even when the user has not actively tried to do anything suspicious (I assume, but I really don't know how these warnings work). I would just try to raise the question with the astropy modeling if it is possible to issue a warning in the end, if fit reaches suspicious point.

**Comment by jianyangli** [comment]
Yes I feel the same.  I raised the question in astropy #modeling slack channel.  Let's see what people suggest.

**Comment by jianyangli** [comment]
I discovered that we can add a `validator` method for all the parameters in the model class using the `astropy.modeling.Parameter.validator` property as a decorator.  Now the model class will issue a warning only when the parameter is assigned, but not every time the model is evaluated.  Hope you are fine with this solution?  @anatheana @mommermi

**Comment by anatheana** [comment]
Sure @jianyangli . I trust on your experience on astropy better than mine.

**Comment by jianyangli** [comment]
Replace #127 by #134

**Comment by jianyangli** [comment]
We have a question for you @anatheana .  In reviewing PR #134 , @mommermi suggested that we make the version of HG12 model in your 2016 paper the default.  This means we name your version `HG12` and the one in Muinonen et al. (2010) `HG12_Orig` or something like that.

What's your suggestions?  Does your model generally work better than the original version, or is your version more "official" than the original version in the IAU system, or should they be regarded the same?  Thank you for your input.

**Comment by anatheana** [comment]
Hi @jianyangli. Tough question. The HG12 from Muinonen 2010 is the 'official' one, so maybe that should be the default. The discontinuity in derivative in that system can produce some practical problems. That is the reason we revised the problem, and using the data from Shevchenko et al., came up with the revised HG12. Now the revised HG12 is continuous in derivative, but also needs the E- and D-types to be tested separately. So the 'fit' from HG12 should actually be so, that the revised HG12 is fitted, and the solution from that fit, E-type fit, and D-type fit is selected, according to smallest RMS-value of these three fits.

All in all, the 2010-system is still the 'official' and approved by IAU.

**Comment by mommermi** [comment]
The motivation behind my suggestion is the strong feeling that people are lazy and will only use whichever model is named `HG12`. Only people that are really familiar with the matter will explore what other flavors of HG12 there are. I think the real question should be: which flavor would you like people to use by default?

**Comment by maxmahlke** [comment]
Hi all, I've been following the discussion while working on my fit implementation in the past weeks. In the end, I went with a Bayesian framework to infer the parameters, which has some advantages when we deal with poorly sampled phase curves over the least squares approach. Once I find some time, I'll write up that example I mentioned and compare the two approaches + showcase the MPC data retrieval a bit.

Funny coincidence, just yesterday I was wondering whether to use HG12 or HG12*, and I got an email alert from this issue on the same topic. In the end, I didn't have much choice, the pymc3 library I use for the Bayesian framework does not handle piecewise-defined functions well, so HG12* was chosen for me here.

**Comment by jianyangli** [comment]
@anatheana @mommermi I just added some notes in the docstrings for `HG12` and `HG12_Pen16`.  Since the `HG12` is still the "official" one approved by IAU, I think we want to keep `HG12` the default, but note the drawbacks of it in the docstring and point users to the improved model version `HG12_Pen16`.  I think in the future we may want to implement some functionality to automatically select the version with the help from @anatheana .  How does this sound to you?

@maxmahlke I think it'll be great to have your new fit approach included in this submodule once you finished coding and testing.  Please keep us posted.  Thank you.

**Comment by jianyangli** [comment]
I'm closing this issue because the related PR #134 has been merged.  But please feel free to open new issues for your Bayesian fitting approach @maxmahlke , and for the possible implementation of automated model selection @anatheana in the future.  Thank you for contributing to `sbpy`!
