### ISSUE TITLE
Initialize DataClass from data rows.

### ISSUE THREAD

**Issue by mkelley** [NASA-Planetary-Science/sbpy#157]
Several times I have wanted to `DataClass.from_rows(rows)`.  This finally formally makes the request!  I would expect it to behave like `astropy.table.Table(rows=rows)`.

**Comment by mommermi** [comment]
I made a workaround to this, which is currently stuck in the development of `sbpy.thermal`. Instead of returning rows, `DataClass` will always return a `Table` - even if it only has a single line. This makes the use of the results much easier, as you can use `DataClass.from_table`. Do you want me to extract it from the upcoming PR and merge it?

**Comment by mkelley** [comment]
What are the circumstances you considered there?  Is this after slicing?  I would have expected `DataClass[i]` to return `DataClass`?

Today's case arises from using `itertools.groupby`, which does return a list of rows.  `.from_table(astropy.table.vstack(group))` is my work around.

**Comment by mommermi** [comment]
Ha. Turns out I haven't yet implemented this. I took a quick stab at it [here](https://github.com/mommermi/sbpy/blob/row_to_table/sbpy/data/core.py#L337). It does what it is supposed to do.

This conversion only happens if an integer is passed to `__getitem__`, so slicing is not involved.

**Comment by mkelley** [comment]
Either that or a slice via self._table[ident:ident+1].  Whichever is more efficient.

But why return a `QTable` instead of `self`?

**Comment by mommermi** [comment]
Ok, I fixed it; you want me to create a PR?

**Comment by mkelley** [comment]
:+1:

**Comment by mkelley** [comment]
#178, done!
